Rebuilding all packages

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -15,130 +15,130 @@ env:
   IMAGE_NAME: ${{ github.repository }}
 
 jobs:
-  # build_containers:
-  #   name: Build containers
-  #   runs-on: ubuntu-20.04
-  #   steps:
+  build_containers:
+    name: Build containers
+    runs-on: ubuntu-20.04
+    steps:
 
-  #   - name: Set up Go 1.16
-  #     uses: actions/setup-go@v1
-  #     with:
-  #       go-version: 1.16
-  #     id: go
+    - name: Set up Go 1.16
+      uses: actions/setup-go@v1
+      with:
+        go-version: 1.16
+      id: go
 
-  #   - name: Install Dependencies
-  #     run: |
-  #       sudo apt-get update && sudo apt-get install -y \
-  #         build-essential \
-  #         libssl-dev \
-  #         uuid-dev \
-  #         libgpgme11-dev \
-  #         squashfs-tools \
-  #         libseccomp-dev \
-  #         pkg-config \
-  #         debootstrap \
-  #         debian-keyring \
-  #         debian-archive-keyring \
-  #         rsync
+    - name: Install Dependencies
+      run: |
+        sudo apt-get update && sudo apt-get install -y \
+          build-essential \
+          libssl-dev \
+          uuid-dev \
+          libgpgme11-dev \
+          squashfs-tools \
+          libseccomp-dev \
+          pkg-config \
+          debootstrap \
+          debian-keyring \
+          debian-archive-keyring \
+          rsync
 
-  #   - name: Install Singularity
-  #     env:
-  #       SINGULARITY_VERSION: 3.5.3
-  #       GOPATH: /tmp/go
-  #     run: |
-  #       mkdir -p $GOPATH
-  #       sudo mkdir -p /usr/local/var/singularity/mnt
-  #       mkdir -p $GOPATH/src/github.com/sylabs
-  #       cd $GOPATH/src/github.com/sylabs
-  #       wget https://github.com/hpcng/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-${SINGULARITY_VERSION}.tar.gz
-  #       tar -xzf singularity-${SINGULARITY_VERSION}.tar.gz
-  #       cd singularity
-  #       ./mconfig -v -p /usr/local
-  #       make -j `nproc 2>/dev/null || echo 1` -C ./builddir all
-  #       sudo make -C ./builddir install
+    - name: Install Singularity
+      env:
+        SINGULARITY_VERSION: 3.5.3
+        GOPATH: /tmp/go
+      run: |
+        mkdir -p $GOPATH
+        sudo mkdir -p /usr/local/var/singularity/mnt
+        mkdir -p $GOPATH/src/github.com/sylabs
+        cd $GOPATH/src/github.com/sylabs
+        wget https://github.com/hpcng/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-${SINGULARITY_VERSION}.tar.gz
+        tar -xzf singularity-${SINGULARITY_VERSION}.tar.gz
+        cd singularity
+        ./mconfig -v -p /usr/local
+        make -j `nproc 2>/dev/null || echo 1` -C ./builddir all
+        sudo make -C ./builddir install
 
 
-  #   - name: Check out code for the container build
-  #     uses: actions/checkout@v2
+    - name: Check out code for the container build
+      uses: actions/checkout@v2
 
-  #   - name: Set release version if is a release
-  #     if: startsWith(github.event.ref, 'refs/tags/v')
-  #     run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
+    - name: Set release version if is a release
+      if: startsWith(github.event.ref, 'refs/tags/v')
+      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
 
-  #   - name: Set release version if not a release
-  #     if: false == startsWith(github.event.ref, 'refs/tags/v')
-  #     run: echo "RELEASE_VERSION=test" >> $GITHUB_ENV
+    - name: Set release version if not a release
+      if: false == startsWith(github.event.ref, 'refs/tags/v')
+      run: echo "RELEASE_VERSION=test" >> $GITHUB_ENV
 
-  #   - name: Build Singularity container
-  #     env:
-  #       SINGULARITY_RECIPE: Singularity.def
-  #       OUTPUT_CONTAINER: mykrobe_${{env.RELEASE_VERSION}}.img
-  #     run: |
-  #       ls
-  #       if [ -f "${SINGULARITY_RECIPE}" ]; then
-  #           sudo -E singularity build ${OUTPUT_CONTAINER} ${SINGULARITY_RECIPE}
-  #       else
-  #           echo "${SINGULARITY_RECIPE} is not found."
-  #           echo "Present working directory: $PWD"
-  #           ls
-  #       fi
+    - name: Build Singularity container
+      env:
+        SINGULARITY_RECIPE: Singularity.def
+        OUTPUT_CONTAINER: mykrobe_${{env.RELEASE_VERSION}}.img
+      run: |
+        ls
+        if [ -f "${SINGULARITY_RECIPE}" ]; then
+            sudo -E singularity build ${OUTPUT_CONTAINER} ${SINGULARITY_RECIPE}
+        else
+            echo "${SINGULARITY_RECIPE} is not found."
+            echo "Present working directory: $PWD"
+            ls
+        fi
 
-  #   - name: Release
-  #     if: startsWith(github.event.ref, 'refs/tags/v')
-  #     uses: softprops/action-gh-release@v1
-  #     with:
-  #       files: mykrobe*.img
-  #       draft: true
-  #     env:
-  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    - name: Release
+      if: startsWith(github.event.ref, 'refs/tags/v')
+      uses: softprops/action-gh-release@v1
+      with:
+        files: mykrobe*.img
+        draft: true
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-  # mac_build:
-  #   name: Build mac os command line
-  #   runs-on: macos-11
-  #   steps:
+  mac_build:
+    name: Build mac os command line
+    runs-on: macos-11
+    steps:
 
-  #   - name: Install dependencies
-  #     run: |
-  #       pip3 install cython requests wheel tox pyinstaller
+    - name: Install dependencies
+      run: |
+        pip3 install cython requests wheel tox pyinstaller
 
-  #   - name: Check out code for the build
-  #     uses: actions/checkout@v2
+    - name: Check out code for the build
+      uses: actions/checkout@v2
 
-  #   - name: Set release version if is a release
-  #     if: startsWith(github.event.ref, 'refs/tags/v')
-  #     run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
+    - name: Set release version if is a release
+      if: startsWith(github.event.ref, 'refs/tags/v')
+      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
 
-  #   - name: Set release version if not a release
-  #     if: false == startsWith(github.event.ref, 'refs/tags/v')
-  #     run: echo "RELEASE_VERSION=test" >> $GITHUB_ENV
+    - name: Set release version if not a release
+      if: false == startsWith(github.event.ref, 'refs/tags/v')
+      run: echo "RELEASE_VERSION=test" >> $GITHUB_ENV
 
-  #   - name: Test and build command line tarball
-  #     env:
-  #       OUTPUT_TARBALL: mykrobe.command_line.osx.${{env.RELEASE_VERSION}}.tar.gz
-  #     run: |
-  #       # mongod default data directory is /data/db, which is not writeable.
-  #       mkdir $HOME/mongodb_data
-  #       chown -R `id -un` $HOME/mongodb_data
-  #       sudo mongod --dbpath=$HOME/mongodb_data --quiet &> /dev/null &
-  #       sleep 3s
-  #       rm -rf .tox
-  #       sudo tox
-  #       sudo pip3 install .
-  #       mykrobe panels update_metadata --panels_dir src/mykrobe/data
-  #       mykrobe panels update_species --panels_dir src/mykrobe/data --debug all
-  #       cd dist
-  #       pyinstaller --workpath='./pyinstaller_build/binary_cache' --distpath='./pyinstaller_build' mykrobe_atlas_pyinstaller.spec
-  #       cd pyinstaller_build
-  #       tar cvfz ../../${OUTPUT_TARBALL} mykrobe_atlas/
+    - name: Test and build command line tarball
+      env:
+        OUTPUT_TARBALL: mykrobe.command_line.osx.${{env.RELEASE_VERSION}}.tar.gz
+      run: |
+        # mongod default data directory is /data/db, which is not writeable.
+        mkdir $HOME/mongodb_data
+        chown -R `id -un` $HOME/mongodb_data
+        sudo mongod --dbpath=$HOME/mongodb_data --quiet &> /dev/null &
+        sleep 3s
+        rm -rf .tox
+        sudo tox
+        sudo pip3 install .
+        mykrobe panels update_metadata --panels_dir src/mykrobe/data
+        mykrobe panels update_species --panels_dir src/mykrobe/data --debug all
+        cd dist
+        pyinstaller --workpath='./pyinstaller_build/binary_cache' --distpath='./pyinstaller_build' mykrobe_atlas_pyinstaller.spec
+        cd pyinstaller_build
+        tar cvfz ../../${OUTPUT_TARBALL} mykrobe_atlas/
 
-  #   - name: Release
-  #     if: startsWith(github.event.ref, 'refs/tags/v')
-  #     uses: softprops/action-gh-release@v1
-  #     with:
-  #       files: mykrobe.command_line.osx.*.tar.gz
-  #       draft: true
-  #     env:
-  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    - name: Release
+      if: startsWith(github.event.ref, 'refs/tags/v')
+      uses: softprops/action-gh-release@v1
+      with:
+        files: mykrobe.command_line.osx.*.tar.gz
+        draft: true
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   windows_build:
     name: Build Windows command line
